### ISSUE TITLE
Center on the img

### ISSUE THREAD

**Issue by zeusro** [jhauraw/axiom#2]
Hey guy, I love your theme and use it on my new project: https://p-program.github.io/

But there is a little issue : If the picture has no enough widths，it would no to be  center on the screen ，so I overwrite css in `custom.css`

```css
.mb-2 {
    margin: 0 auto ;
}
```

What do you think ？
